[package]
name = "modlearning"
version = "0.1.0"
edition = "2021"


[lib]
name = "calculator"
path = "src/calculator/calculator.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
